### ISSUE TITLE
mystery code about IoU calculate ?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#303]
in chainercv/chainercv/utils/bbox/bbox_iou.py

the below code is very hard to understand, Could you explain to me about how exactly this code works?

```def bbox_iou(bbox_a, bbox_b):
    if bbox_a.shape[1] != 4 or bbox_b.shape[1] != 4:
        raise IndexError
    xp = cuda.get_array_module(bbox_a)

    # top left
    tl = xp.maximum(bbox_a[:, None, :2], bbox_b[:, :2])
    # bottom right
    br = xp.minimum(bbox_a[:, None, 2:], bbox_b[:, 2:])

    area_i = xp.prod(br - tl, axis=2) * (tl < br).all(axis=2)
    area_a = xp.prod(bbox_a[:, 2:] - bbox_a[:, :2], axis=1)
    area_b = xp.prod(bbox_b[:, 2:] - bbox_b[:, :2], axis=1)
    return area_i / (area_a[:, None] + area_b - area_i)```

**Comment by yuyu2172** [comment]
It calculates intersection over union between bounding boxes in `bbox_a` and `bbox_b`.
The formula to calculate IoU from a pair of bounding boxes can be found in the link below.

https://en.wikipedia.org/wiki/Jaccard_index

Perhaps, this is a little bit difficult to understand in the first hand because the code processes IoUs between collections of bounding boxes.

**Comment by sharpstill** [comment]
A little bit? I must say you are really very powerful numpy user. very impressive code

**Comment by sharpstill** [comment]
how to use numpy like you？ do you have any learning numpy suggestion？

**Comment by yuyu2172** [comment]
Thanks. This was a work by @Hakuyume .
It is always better to start from easy code and optimize it later.

If you have any more questions, please re-open this.
