### ISSUE TITLE
why l - 1 in def _suppress ?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#320]
in https://github.com/chainer/chainercv/blob/master/chainercv/links/model/faster_rcnn/faster_rcnn.py#L237
there is `label.append((l - 1) * np.ones((len(keep),)))`
because self.n_class contains background class label.
but the l-1 will range= [0, class_num - 2]
so **foreground** label may also probaby be **0**??
why l - 1 in this code?

**Comment by yuyu2172** [comment]
Yes, foreground labels have value in range `[0, n_class -2]` or `[0, n_fg_class - 1]`.

`n_class` is the total number of classes including the background.
Since detection results do not contain any background labels, any labels exposed to code outside of models are in range without the background.
Also, inside of a model, labels can be the background.
The `-1` is necessary to convert class labels from a convention including the background to one without it.
