### ISSUE TITLE
The loss becomes Nan

### ISSUE THREAD

**Issue by 1991viet** [chainer/chainercv#326]
Hi contributors,
I have a question, hope that you could help me. I run your Faster RCNN model. It is totally fine, your model worked perfectly. I want to make a similar model for oriented bounding box. I changed some parts of your code (dataset, nms, iou, bbox2loc, loc2bbox and so on). Bounding box is also changed from 4 variables (top left, bottom right vertices) to 5 variables (center verex, width, height and angle).Of course I also checked my code to make sure that the parts I modify produce the same output as your model does. And my new model also run. Over the first several thousand epochs, the log printed out is very similar to the log I could see when I run your original model. But after that, all the losses printed out on terminal become Nan. Could I ask you, in chainer in general and in chainercv in particular, what could be the reasons making loss become Nan ? Or if you have any suggestion about which could be the reason making that abnormal behaviour of my model, it is also valuable to me.
I attach below the log over first epochs, as you could see, it look very similar to your model's
![screen shot 2017-07-07 at 12 42 26 am](https://user-images.githubusercontent.com/15526232/27935846-df799522-62ad-11e7-97a6-36e4786635cb.png)

Thank you so muchhh

**Comment by yuyu2172** [comment]
Interesting approach.
Since I don't have an access to your version of NMS, bbo_iou, bbox2loc, loc2bbox, I can not say exactly how the problem is caused.
For the cause of the abnormal behaviors, here are my guesses.

+ If you are using CPU for training, we recently found a bug in RoIPooling2d (https://github.com/chainer/chainer/pull/2872)
+ If you have a ground truth bounding box that has zero length, `bbox2loc` returns nan. Have you succeeded in iterating an entire epoch? If nan arises at particular point in the epoch consistently, you can guess that problem is occurring.

You did not mention RPN in your comment. Are you using regular bounding boxes for RPN/RoIPooling?

**Comment by sharpstill** [comment]
@1991viet @yuyu2172 I have encounter the same issue when I modify a little code and use new data to train. The solution may work:
1. use **shuffle=True** in train_iter
2. use optimizor : **Adagrad** may work

**Comment by 1991viet** [comment]
Thank both of you so much :)
