### ISSUE TITLE
how to create my datasets

### ISSUE THREAD

**Issue by Horisu** [chainer/chainercv#353]
I will prepare images and bounding boxes.
How can this libraries read images' path and which files souhld I write bounding boxes?
Where is the documentation and the sample directory to craete datasets from images and train it ?

**Comment by yuyu2172** [comment]
A dataset loader class should have an array like interface: `__getitem__`, `__len__`.
Usually, people create a dataset loader by inheriting from a class :chainer.dataset.DatasetMixin`.

In the case of a detection dataset, it needs to return three values when indexed: `img`, `bbox`, `label`.
More precise definition of the interface can be found here.
https://github.com/chainer/chainercv/blob/master/chainercv/utils/testing/assertions/assert_is_detection_dataset.py
Your dataset should pass the assertion method.

Here is an example of a detection dataset.
https://github.com/chainer/chainercv/blob/master/chainercv/datasets/voc/voc_detection_dataset.py

**Comment by Horisu** [comment]
I can't completely understand.
Why do I have to wirte such scripts only to load images.
It seems to be longer than prediction demo scripts.

**Comment by yuyu2172** [comment]
If you only need the detector in runtime, you do not need to have a detection dataset.
In that case, you can use `utils.read_image` to load an image from a path.
https://github.com/chainer/chainercv/blob/master/examples/ssd/demo.py#L37

If you need to train a model, you need to have a dataset with the interface I mentioned in the previous comment.

**Comment by Horisu** [comment]
It's messy that all people who make datasets have to write their own interface each time.
Aren't there the standard format to prepare images and labels works with prepared standard interface?

**Comment by yuyu2172** [comment]
The interface is defined as I said.
The dataset object needs to pass the test I mentioned previously.
https://github.com/chainer/chainercv/blob/master/chainercv/utils/testing/assertions/assert_is_detection_dataset.py

The implementation is up to you.
I believe this is the right design because there can be multiple ways to store data in the filesystem.
For example some people use `y_min, x_min, y_max, x_max`, but some other use `center_y, center_x, height, width` to represent bounding box.
On top of that, people encode class information differently.
These variation make it very difficult to make a standard data loader for the detection task.

**Comment by yuyu2172** [comment]
@Horisu 

I created a complete example to train SSD with data annotated by yourself.
Please note that this example assumes that you annotate data with https://github.com/yuyu2172/image-labelling-tool.
https://github.com/yuyu2172/image-labelling-tool/tree/master/examples/ssd#example

**Comment by yuyu2172** [comment]
This question is answered in #391.
